apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kafka.fullname" . }}-lb-reader
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafka.fullname" . }}-lb-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kafka.fullname" . }}-lb-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "kafka.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
spec:
  # Internal Port 9092, External Port 9094
  type: LoadBalancer
  selector:
    app: {{ include "kafka.fullname" . }}
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
    - name: external
      port: 9094
      targetPort: 9094
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka.fullname" . }}
spec:
  serviceName: {{ include "kafka.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kafka.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "kafka.fullname" . }}
    spec:
      serviceAccountName: {{ include "kafka.fullname" . }}
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-permissions
          image: busybox:latest
          command: ["sh", "-c", "chown -R 1000:1000 /var/lib/kafka/data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data
      containers:
        - name: kafka
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          securityContext:
            runAsUser: 1000
          command:
            - sh
            - -c
            - |
              echo "Waiting for LoadBalancer IP..."
              TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              LB_IP=""
              while [ -z "$LB_IP" ]; do
                LB_IP=$(wget -qO- --header "Authorization: Bearer $TOKEN" --no-check-certificate https://kubernetes.default.svc/api/v1/namespaces/{{ .Release.Namespace }}/services/{{ include "kafka.fullname" . }} | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | head -n 1)
                [ -z "$LB_IP" ] && sleep 5
              done
              
              echo "Discovered LB IP: $LB_IP"
              export KAFKA_ADVERTISED_LISTENERS="INTERNAL://{{ include "kafka.fullname" . }}:9092,EXTERNAL://${LB_IP}:9094"
              /etc/kafka/docker/run
          env:
            - name: CLUSTER_ID
              value: {{ .Values.kafka.clusterId | quote }}
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data/logs"
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.kafka.storage.className }}
        resources:
          requests:
            storage: {{ .Values.kafka.storage.size }}