apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-headless
spec:
  clusterIP: None
  selector:
    app: {{ include "kafka.fullname" . }}
  ports:
    - name: client
      port: 9092
    - name: controller
      port: 9093

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "kafka.fullname" . }}
  ports:
    - name: client
      port: 9092

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka.fullname" . }}
spec:
  serviceName: {{ include "kafka.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kafka.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "kafka.fullname" . }}
    spec:
      containers:
        - name: kafka
          image: {{ .Values.image }}
          # We use a shell command to extract the integer from the Pod name (gai-0 -> 0)
          command:
            - sh
            - -c
            - |
              export KAFKA_NODE_ID=${HOSTNAME##*-}
              export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://${HOSTNAME}.{{ include "kafka.fullname" . }}-headless:9092"
              /etc/kafka/docker/run
          env:
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: {{ range $i, $e := until (int .Values.replicaCount) }}{{ if $i }},{{ end }}{{ $i }}@{{ $.Release.Name }}-kafka-{{ $i }}.{{ $.Release.Name }}-kafka-headless:9093{{ end }}
            - name: KAFKA_CLUSTER_ID
              value: {{ .Values.clusterId | quote }}
            # Set internal replication to match cluster size
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: {{ .Values.replicaCount | quote }}
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: {{ .Values.replicaCount | quote }}
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
          resources:
            {{- toYaml .Values.resources.kafka | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.storage.storageClass }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}