{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka.ui.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kafka.ui.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "kafka.ui.fullname" . }}
    spec:
      containers:
        - name: kafka-ui
          image: {{ .Values.ui.image }}
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: {{ .Release.Name | quote }}
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "{{ include "kafka.fullname" . }}:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.ui.fullname" . }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ include "kafka.ui.fullname" . }}
{{- end }}